log:
    - name: root
      level: info
      formatter: "%d%T%m%n"
      appender: 
          - type: FileLogAppender
            file: log.txt
          - type: StdoutLogAppender
    - name: system
      level: debug
      formatter: "%d%T%m%n"
      appender: 
          - type: FileLogAppender
            file: log.txt
          - type: StdoutLogAppender
system:
    port: 9000
    float: 1.22
    vec_int: [1, 2]
    list_int: [20, 11]
    set_int: [100, 300]
    unordered_set_int:
        - 111111
        - 222222
    map_str_int: {"1": 11111, "2": 2222222}
    unordered_map_str_int:
        1: 1211111
        2: 4444444

class:
    person:
        name: "lll"
        age: 1000
        sex: true
        ints:
            - 1
            - 2
            - 2
    person_map:
        p_map_1:
            name: "222"
            age: 30000
            sex: false
            ints: [1]
        p_map_2:
            name: "3333"
            age: 40000
            sex: true
            ints: [1]
    person_map_vec:
        p_map_vec_1: 
            - name: "3"
              age: 111
              sex: true
              ints:
            - name: "4"
              age: 111
              sex: true
              ints: